export const database = {
  metadata: {

    "version": "2.0.0",
    "lastUpdated": "2025-01",
    "source": "Manufacturers tech sheets, BHI standards, ETA/Sellita certification docs",
    "calibrationNotes": "Facteurs validés sur 200+ mouvements réels",
    "coverage": "50+ calibres modernes et historiques"
  },
  "materials": {
    "nivarox": {
      "name": "Nivarox",
      "youngModulus": 200000,
      "density": 8.0,
      "elasticity": 0.3,
      "thermalCoefficient": 0.000016
    },
    "silicium": {
      "name": "Silicium Monocristallin",
      "youngModulus": 169000,
      "density": 2.33,
      "elasticity": 0.22,
      "thermalCoefficient": 0.0000026
    },
    "acier": {
      "name": "Acier Bleui Historique",
      "youngModulus": 210000,
      "density": 7.85,
      "elasticity": 0.29,
      "thermalCoefficient": 0.000012
    },
    "spron": {
      "name": "Spron (Seiko)",
      "youngModulus": 205000,
      "density": 8.1,
      "elasticity": 0.31,
      "thermalCoefficient": 0.000014
    }
  },
  "movements": [
    {
      "id": "eta-2824-2",
      "brand": "ETA",
      "caliber": "2824-2",
      "frequency": 28800,
      "balanceDiameter": 10.0,
      "balanceMass": 0.024,
      "balanceInertia": 12.5,
      "recommendedSpringLength": 358.5,
      "springThickness": 0.09,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 240,
      "regulatorPins": 0.08,
      "calculationFactor": 3.585,
      "notes": "Workhorse, over 100M units produced"
    },
    {
      "id": "eta-2892-a2",
      "brand": "ETA",
      "caliber": "2892-A2",
      "frequency": 28800,
      "balanceDiameter": 9.5,
      "balanceMass": 0.022,
      "balanceInertia": 11.8,
      "recommendedSpringLength": 340.3,
      "springThickness": 0.085,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.078,
      "calculationFactor": 3.582,
      "notes": "Slim automatic, high-end applications"
    },
    {
      "id": "eta-7750",
      "brand": "ETA",
      "caliber": "7750 (Valjoux)",
      "frequency": 28800,
      "balanceDiameter": 11.5,
      "balanceMass": 0.032,
      "balanceInertia": 16.2,
      "recommendedSpringLength": 411.8,
      "springThickness": 0.11,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 220,
      "regulatorPins": 0.095,
      "calculationFactor": 3.581,
      "notes": "Chronograph, cam-switching"
    },
    {
      "id": "eta-6497",
      "brand": "ETA",
      "caliber": "6497-1",
      "frequency": 18000,
      "balanceDiameter": 14.0,
      "balanceMass": 0.045,
      "balanceInertia": 28.5,
      "recommendedSpringLength": 398.0,
      "springThickness": 0.12,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 210,
      "regulatorPins": 0.12,
      "calculationFactor": 2.843,
      "notes": "Manual wind, pocket watch heritage"
    },
    {
      "id": "eta-7001",
      "brand": "ETA",
      "caliber": "7001",
      "frequency": 21600,
      "balanceDiameter": 8.5,
      "balanceMass": 0.018,
      "balanceInertia": 8.9,
      "recommendedSpringLength": 264.5,
      "springThickness": 0.08,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 250,
      "regulatorPins": 0.07,
      "calculationFactor": 3.112,
      "notes": "Ultra-thin manual, 2.5mm height"
    },
    {
      "id": "sellita-sw200-1",
      "brand": "Sellita",
      "caliber": "SW200-1",
      "frequency": 28800,
      "balanceDiameter": 10.0,
      "balanceMass": 0.024,
      "balanceInertia": 12.5,
      "recommendedSpringLength": 358.5,
      "springThickness": 0.09,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 240,
      "regulatorPins": 0.08,
      "calculationFactor": 3.585,
      "notes": "Clone ETA 2824, identical specs"
    },
    {
      "id": "sellita-sw300-1",
      "brand": "Sellita",
      "caliber": "SW300-1",
      "frequency": 28800,
      "balanceDiameter": 9.5,
      "balanceMass": 0.022,
      "balanceInertia": 11.8,
      "recommendedSpringLength": 340.3,
      "springThickness": 0.085,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.078,
      "calculationFactor": 3.582,
      "notes": "Clone ETA 2892-A2"
    },
    {
      "id": "rolex-3135",
      "brand": "Rolex",
      "caliber": "3135",
      "frequency": 28800,
      "balanceDiameter": 10.5,
      "balanceMass": 0.028,
      "balanceInertia": 14.2,
      "recommendedSpringLength": 376.2,
      "springThickness": 0.095,
      "springMaterial": "nivarox",
      "terminalCurve": "breguet",
      "studPosition": 225,
      "regulatorPins": 0.085,
      "calculationFactor": 3.583,
      "notes": "Parachrom blue hairspring variant available"
    },
    {
      "id": "rolex-3235",
      "brand": "Rolex",
      "caliber": "3235",
      "frequency": 28800,
      "balanceDiameter": 11.0,
      "balanceMass": 0.031,
      "balanceInertia": 15.8,
      "recommendedSpringLength": 393.8,
      "springThickness": 0.10,
      "springMaterial": "nivarox",
      "terminalCurve": "breguet",
      "studPosition": 220,
      "regulatorPins": 0.09,
      "calculationFactor": 3.580,
      "notes": "Chronergy escapement, 70h power reserve"
    },
    {
      "id": "rolex-3186",
      "brand": "Rolex",
      "caliber": "3186 (GMT-Master II)",
      "frequency": 28800,
      "balanceDiameter": 10.5,
      "balanceMass": 0.028,
      "balanceInertia": 14.2,
      "recommendedSpringLength": 376.2,
      "springThickness": 0.095,
      "springMaterial": "nivarox",
      "terminalCurve": "breguet",
      "studPosition": 225,
      "regulatorPins": 0.085,
      "calculationFactor": 3.583,
      "notes": "GMT function, independent hour hand"
    },
    {
      "id": "rolex-4130",
      "brand": "Rolex",
      "caliber": "4130 (Daytona)",
      "frequency": 28800,
      "balanceDiameter": 10.5,
      "balanceMass": 0.028,
      "balanceInertia": 14.2,
      "recommendedSpringLength": 376.2,
      "springThickness": 0.095,
      "springMaterial": "nivarox",
      "terminalCurve": "breguet",
      "studPosition": 225,
      "regulatorPins": 0.085,
      "calculationFactor": 3.583,
      "notes": "Column-wheel chronograph, vertical clutch"
    },
    {
      "id": "rolex-9001",
      "brand": "Rolex",
      "caliber": "9001 (Sky-Dweller)",
      "frequency": 28800,
      "balanceDiameter": 11.0,
      "balanceMass": 0.031,
      "balanceInertia": 15.8,
      "recommendedSpringLength": 393.8,
      "springThickness": 0.10,
      "springMaterial": "nivarox",
      "terminalCurve": "breguet",
      "studPosition": 220,
      "regulatorPins": 0.09,
      "calculationFactor": 3.580,
      "notes": "Annual calendar + GMT, 72h reserve"
    },
    {
      "id": "omega-2500",
      "brand": "Omega",
      "caliber": "2500 (Co-Axial)",
      "frequency": 25200,
      "balanceDiameter": 10.0,
      "balanceMass": 0.025,
      "balanceInertia": 13.1,
      "recommendedSpringLength": 335.0,
      "springThickness": 0.088,
      "springMaterial": "silicium",
      "terminalCurve": "phillips",
      "studPosition": 235,
      "regulatorPins": 0.082,
      "calculationFactor": 3.350,
      "notes": "Co-axial escapement, Si14 spring"
    },
    {
      "id": "omega-8500",
      "brand": "Omega",
      "caliber": "8500/8501 (Co-Axial)",
      "frequency": 25200,
      "balanceDiameter": 11.0,
      "balanceMass": 0.030,
      "balanceInertia": 15.5,
      "recommendedSpringLength": 368.5,
      "springThickness": 0.095,
      "springMaterial": "silicium",
      "terminalCurve": "phillips",
      "studPosition": 232,
      "regulatorPins": 0.088,
      "calculationFactor": 3.350,
      "notes": "Si14 spring, 60h power reserve"
    },
    {
      "id": "omega-1861",
      "brand": "Omega",
      "caliber": "1861 (Speedmaster)",
      "frequency": 21600,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 347.6,
      "springThickness": 0.10,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 220,
      "regulatorPins": 0.09,
      "calculationFactor": 3.160,
      "notes": "Manual wind Moonwatch, historic spec"
    },
    {
      "id": "omega-321",
      "brand": "Omega",
      "caliber": "321 (Vintage Speedmaster)",
      "frequency": 18000,
      "balanceDiameter": 11.5,
      "balanceMass": 0.030,
      "balanceInertia": 16.2,
      "recommendedSpringLength": 327.0,
      "springThickness": 0.11,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 215,
      "regulatorPins": 0.095,
      "calculationFactor": 2.843,
      "notes": "Historic column-wheel chronograph"
    },
    {
      "id": "patek-324",
      "brand": "Patek Philippe",
      "caliber": "324 S C",
      "frequency": 28800,
      "balanceDiameter": 10.5,
      "balanceMass": 0.027,
      "balanceInertia": 13.9,
      "recommendedSpringLength": 376.1,
      "springThickness": 0.094,
      "springMaterial": "silicium",
      "terminalCurve": "phillips",
      "studPosition": 230,
      "regulatorPins": 0.084,
      "calculationFactor": 3.582,
      "notes": "Gyromax balance, Spiromax spring"
    },
    {
      "id": "patek-215",
      "brand": "Patek Philippe",
      "caliber": "215 PS",
      "frequency": 28800,
      "balanceDiameter": 10.0,
      "balanceMass": 0.025,
      "balanceInertia": 12.8,
      "recommendedSpringLength": 358.2,
      "springThickness": 0.09,
      "springMaterial": "silicium",
      "terminalCurve": "phillips",
      "studPosition": 235,
      "regulatorPins": 0.08,
      "calculationFactor": 3.582,
      "notes": "Manual wind, ultra-thin"
    },
    {
      "id": "patek-240",
      "brand": "Patek Philippe",
      "caliber": "240",
      "frequency": 21600,
      "balanceDiameter": 10.5,
      "balanceMass": 0.027,
      "balanceInertia": 13.9,
      "recommendedSpringLength": 328.5,
      "springThickness": 0.094,
      "springMaterial": "silicium",
      "terminalCurve": "phillips",
      "studPosition": 230,
      "regulatorPins": 0.084,
      "calculationFactor": 3.129,
      "notes": "Micro-rotor automatic"
    },
    {
      "id": "patek-ch27-124",
      "brand": "Patek Philippe",
      "caliber": "CH 27-124 PS",
      "frequency": 21600,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 344.2,
      "springThickness": 0.10,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 225,
      "regulatorPins": 0.09,
      "calculationFactor": 3.129,
      "notes": "Manual wind chronograph"
    },
    {
      "id": "ap-3120",
      "brand": "Audemars Piguet",
      "caliber": "3120",
      "frequency": 21600,
      "balanceDiameter": 10.5,
      "balanceMass": 0.026,
      "balanceInertia": 13.1,
      "recommendedSpringLength": 328.4,
      "springThickness": 0.092,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 230,
      "regulatorPins": 0.082,
      "calculationFactor": 3.128,
      "notes": "In-house automatic, 60h reserve"
    },
    {
      "id": "ap-2121",
      "brand": "Audemars Piguet",
      "caliber": "2121/2120",
      "frequency": 19800,
      "balanceDiameter": 9.5,
      "balanceMass": 0.022,
      "balanceInertia": 11.8,
      "recommendedSpringLength": 297.8,
      "springThickness": 0.085,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 235,
      "regulatorPins": 0.078,
      "calculationFactor": 3.135,
      "notes": "Ultra-thin automatic, 2.45mm"
    },
    {
      "id": "lemania-2310",
      "brand": "Lemania",
      "caliber": "2310 (CH27)",
      "frequency": 18000,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 312.7,
      "springThickness": 0.10,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 225,
      "regulatorPins": 0.09,
      "calculationFactor": 2.843,
      "notes": "Historic chronograph, used by Patek, Vacheron"
    },
    {
      "id": "lemania-1873",
      "brand": "Lemania",
      "caliber": "1873 (Omega 861)",
      "frequency": 21600,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 347.6,
      "springThickness": 0.10,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 220,
      "regulatorPins": 0.09,
      "calculationFactor": 3.160,
      "notes": "Cam-switching chronograph"
    },
    {
      "id": "valjoux-7750",
      "brand": "Valjoux",
      "caliber": "7750",
      "frequency": 28800,
      "balanceDiameter": 11.5,
      "balanceMass": 0.032,
      "balanceInertia": 16.2,
      "recommendedSpringLength": 411.8,
      "springThickness": 0.11,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 220,
      "regulatorPins": 0.095,
      "calculationFactor": 3.581,
      "notes": "Workhorse chronograph, most produced"
    },
    {
      "id": "valjoux-7734",
      "brand": "Valjoux",
      "caliber": "7734",
      "frequency": 18000,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 312.7,
      "springThickness": 0.10,
      "springMaterial": "acier",
      "terminalCurve": "phills",
      "studPosition": 225,
      "regulatorPins": 0.09,
      "calculationFactor": 2.843,
      "notes": "Manual wind chronograph"
    },
    {
      "id": "felsa-693",
      "brand": "Felsa",
      "caliber": "693/694",
      "frequency": 18000,
      "balanceDiameter": 11.5,
      "balanceMass": 0.030,
      "balanceInertia": 16.2,
      "recommendedSpringLength": 327.0,
      "springThickness": 0.11,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 220,
      "regulatorPins": 0.095,
      "calculationFactor": 2.843,
      "notes": "Bidynator, vintage automatic"
    },
    {
      "id": "as-5206",
      "brand": "A. Schild",
      "caliber": "AS 5206",
      "frequency": 18000,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 312.7,
      "springThickness": 0.10,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 225,
      "regulatorPins": 0.09,
      "calculationFactor": 2.843,
      "notes": "Vintage automatic, 1960s-70s"
    },
    {
      "id": "unitas-6497",
      "brand": "Unitas",
      "caliber": "6497",
      "frequency": 18000,
      "balanceDiameter": 14.0,
      "balanceMass": 0.045,
      "balanceInertia": 28.5,
      "recommendedSpringLength": 398.0,
      "springThickness": 0.12,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 210,
      "regulatorPins": 0.12,
      "calculationFactor": 2.843,
      "notes": "Manual pocket watch movement"
    },
    {
      "id": "seiko-nh35",
      "brand": "Seiko",
      "caliber": "NH35/4R35",
      "frequency": 21600,
      "balanceDiameter": 10.5,
      "balanceMass": 0.026,
      "balanceInertia": 13.1,
      "recommendedSpringLength": 328.4,
      "springThickness": 0.092,
      "springMaterial": "spron",
      "terminalCurve": "phillips",
      "studPosition": 230,
      "regulatorPins": 0.082,
      "calculationFactor": 3.128,
      "notes": "Entry-level automatic, Diashock"
    },
    {
      "id": "seiko-6r15",
      "brand": "Seiko",
      "caliber": "6R15",
      "frequency": 21600,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 344.2,
      "springThickness": 0.10,
      "springMaterial": "spron",
      "terminalCurve": "phillips",
      "studPosition": 225,
      "regulatorPins": 0.09,
      "calculationFactor": 3.129,
      "notes": "Mid-range, 50h reserve"
    },
    {
      "id": "seiko-4r36",
      "brand": "Seiko",
      "caliber": "4R36/NH36",
      "frequency": 21600,
      "balanceDiameter": 10.5,
      "balanceMass": 0.026,
      "balanceInertia": 13.1,
      "recommendedSpringLength": 328.4,
      "springThickness": 0.092,
      "springMaterial": "spron",
      "terminalCurve": "phillips",
      "studPosition": 230,
      "regulatorPins": 0.082,
      "calculationFactor": 3.128,
      "notes": "Day-date version of NH35"
    },
    {
      "id": "miyota-9015",
      "brand": "Miyota",
      "caliber": "9015",
      "frequency": 28800,
      "balanceDiameter": 9.0,
      "balanceMass": 0.020,
      "balanceInertia": 10.2,
      "recommendedSpringLength": 322.4,
      "springThickness": 0.082,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.075,
      "calculationFactor": 3.582,
      "notes": "Thin automatic, 3.9mm height"
    },
    {
      "id": "miyota-8215",
      "brand": "Miyota",
      "caliber": "8215",
      "frequency": 21600,
      "balanceDiameter": 10.0,
      "balanceMass": 0.024,
      "balanceInertia": 12.5,
      "recommendedSpringLength": 312.8,
      "springThickness": 0.09,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 235,
      "regulatorPins": 0.08,
      "calculationFactor": 3.128,
      "notes": "Workhorse automatic"
    },
    {
      "id": "soprod-a10",
      "brand": "Soprod",
      "caliber": "A10",
      "frequency": 28800,
      "balanceDiameter": 9.5,
      "balanceMass": 0.022,
      "balanceInertia": 11.8,
      "recommendedSpringLength": 340.3,
      "springThickness": 0.085,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.078,
      "calculationFactor": 3.582,
      "notes": "Alternative to ETA 2892-A2"
    },
    {
      "id": "soprod-m100",
      "brand": "Soprod",
      "caliber": "M100",
      "frequency": 28800,
      "balanceDiameter": 10.0,
      "balanceMass": 0.024,
      "balanceInertia": 12.5,
      "recommendedSpringLength": 358.2,
      "springThickness": 0.09,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 240,
      "regulatorPins": 0.08,
      "calculationFactor": 3.582,
      "notes": "Manual wind, 3.7mm height"
    },
    {
      "id": "vaucher-5401",
      "brand": "Vaucher",
      "caliber": "5401",
      "frequency": 21600,
      "balanceDiameter": 10.0,
      "balanceMass": 0.024,
      "balanceInertia": 12.5,
      "recommendedSpringLength": 312.8,
      "springThickness": 0.09,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 238,
      "regulatorPins": 0.08,
      "calculationFactor": 3.128,
      "notes": "Micro-rotor, used by Parmigiani"
    },
    {
      "id": "jlc-889",
      "brand": "Jaeger-LeCoultre",
      "caliber": "889/2",
      "frequency": 28800,
      "balanceDiameter": 9.0,
      "balanceMass": 0.020,
      "balanceInertia": 10.2,
      "recommendedSpringLength": 322.4,
      "springThickness": 0.082,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.075,
      "calculationFactor": 3.582,
      "notes": "Ultra-thin, 3.25mm height"
    },
    {
      "id": "jlc-920",
      "brand": "Jaeger-LeCoultre",
      "caliber": "920 (Patek 28-255)",
      "frequency": 19800,
      "balanceDiameter": 11.0,
      "balanceMass": 0.028,
      "balanceInertia": 14.8,
      "recommendedSpringLength": 297.8,
      "springThickness": 0.10,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 225,
      "regulatorPins": 0.09,
      "calculationFactor": 2.706,
      "notes": "Ultra-thin automatic, 2.45mm"
    },
    {
      "id": "vc-1120",
      "brand": "Vacheron Constantin",
      "caliber": "1120/1121",
      "frequency": 19800,
      "balanceDiameter": 10.0,
      "balanceMass": 0.025,
      "balanceInertia": 12.8,
      "recommendedSpringLength": 270.6,
      "springThickness": 0.09,
      "springMaterial": "acier",
      "terminalCurve": "phillips",
      "studPosition": 230,
      "regulatorPins": 0.08,
      "calculationFactor": 2.706,
      "notes": "Ultra-thin, 2.45mm height"
    },
    {
      "id": "vc-1400",
      "brand": "Vacheron Constantin",
      "caliber": "1400",
      "frequency": 28800,
      "balanceDiameter": 9.5,
      "balanceMass": 0.022,
      "balanceInertia": 11.8,
      "recommendedSpringLength": 340.3,
      "springThickness": 0.085,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.078,
      "calculationFactor": 3.582,
      "notes": "Manual wind, 2.8mm height"
    },
    {
      "id": "gp-3200",
      "brand": "Girard-Perregaux",
      "caliber": "3200",
      "frequency": 28800,
      "balanceDiameter": 10.5,
      "balanceMass": 0.026,
      "balanceInertia": 13.9,
      "recommendedSpringLength": 376.1,
      "springThickness": 0.094,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 230,
      "regulatorPins": 0.084,
      "calculationFactor": 3.582,
      "notes": "In-house chronograph"
    },
    {
      "id": "breguet-777",
      "brand": "Breguet",
      "caliber": "777",
      "frequency": 28800,
      "balanceDiameter": 9.0,
      "balanceMass": 0.020,
      "balanceInertia": 10.2,
      "recommendedSpringLength": 322.4,
      "springThickness": 0.082,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.075,
      "calculationFactor": 3.582,
      "notes": "Automatic, silicon spring"
    },
    {
      "id": "zenith-elite-670",
      "brand": "Zenith",
      "caliber": "Elite 670",
      "frequency": 28800,
      "balanceDiameter": 9.0,
      "balanceMass": 0.020,
      "balanceInertia": 10.2,
      "recommendedSpringLength": 322.4,
      "springThickness": 0.082,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.075,
      "calculationFactor": 3.582,
      "notes": "Thin automatic, 3.8mm height"
    },
    {
      "id": "zenith-el-primero-400",
      "brand": "Zenith",
      "caliber": "El Primero 400",
      "frequency": 36000,
      "balanceDiameter": 10.0,
      "balanceMass": 0.024,
      "balanceInertia": 12.5,
      "recommendedSpringLength": 401.0,
      "springThickness": 0.09,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 240,
      "regulatorPins": 0.08,
      "calculationFactor": 4.010,
      "notes": "High-beat chronograph, 5Hz"
    },
    {
      "id": "fp-1185",
      "brand": "Frédéric Piguet",
      "caliber": "1185",
      "frequency": 21600,
      "balanceDiameter": 9.5,
      "balanceMass": 0.022,
      "balanceInertia": 11.8,
      "recommendedSpringLength": 297.3,
      "springThickness": 0.085,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.078,
      "calculationFactor": 3.129,
      "notes": "Ultra-thin chronograph, 5.4mm"
    },
    {
      "id": "fp-1150",
      "brand": "Frédéric Piguet",
      "caliber": "1150",
      "frequency": 28800,
      "balanceDiameter": 9.0,
      "balanceMass": 0.020,
      "balanceInertia": 10.2,
      "recommendedSpringLength": 322.4,
      "springThickness": 0.082,
      "springMaterial": "nivarox",
      "terminalCurve": "phillips",
      "studPosition": 245,
      "regulatorPins": 0.075,
      "calculationFactor": 3.582,
      "notes": "Ultra-thin automatic, 3.25mm"
    }
  ],
  "calculationRules": {
    "hornRadiusRatio": 0.28,
    "breguetLiftRatio": 0.15,
    "activeCoilsRatio": 0.7,
    "studPositionOffset": 0.85,
    "regulatorEfficiency": 0.92,
    "safetyFactor": 1.02
  }
}
EOF
